<?php

return [
    // ========================
    // Sistema de Eventos
    // ========================

    'sobrevivencia' => [
        "Nada acontece",
        "Você ouve um barulho desconhecido",
        "Você ouve ou vê algo muito útil",
        "O chão cai",
        "Você ouve ou vê algo verdadeiramente útil",
        "Você encontra um comerciante de alguma área da região",
        "Você encontra um NPC conhecido ou novo na região",
        "Você encontra um NPC com vontade de aventura",
        "Você encontra um NPC útil",
        "Você encontra um NPC verdadeiramente útil",
        "A PIOR situação acontece...",
        "A MELHOR situação acontece...",
        "Um nevoeiro ou neblina domina a região até a noite",
        "Um nevoeiro ou neblina domina a região até amanhecer",
        "Uma onda de calor domina a região",
        "Uma onda de frio domina a região",
        "Uma onda climática estacional domina a região nesse dia",
        "Um item da base é saqueado por alguém ou algo, enquanto em jornada",
        "Um item valioso da base é saqueado por alguém ou algo, enquanto em jornada",
        "Um item é encontrado",
        "Um item valioso é encontrado",
        "Armas de fogo travam ou ficam com defeito na aventura",
        "Uma arma do grupo enferruja em jornada",
        "Uma arma do grupo enferruja na base",
        "Um caminho de sorte é guiado sobre a missão",
        "Um rastro de um inimigo fica aparente na região",
        "Um rastro de uma criatura fica aparente na região",
        "Um rastro de uma criatura Apex ou maior fica aparente na região",
        "Um rastro de um tesouro ou templo fica aparente na região",
        "Um rastro de um 'drop' fica aparente no céu",
        "Um conjunto de recursos animais fica aparente na região",
        "Um tipo de minério fica aparente na região",
        "Um tipo de minério raro fica aparente na região",
        "Um tipo de joia aparece nas praias próximas",
        "Um item aparece nas praias próximas",
        "Um náufrago aparece nas praias próximas",
        "Um item aparece no meio da floresta mais próxima",
        "Uma carcaça fica aparente na praia",
        "Um mega tesouro ou estrutura abandonada é encontrada nas praias mais próximas",
        "Um mega tesouro ou estrutura abandonada é encontrada nas florestas mais próximas",
        "Uma carcaça de um inimigo fica aparente na região",
        "Uma carcaça de um inimigo com itens fica à mostra na região",
        "Você lembra de momentos bons, recupera +20 de Sanidade",
        "Você lembra de momentos bons, recupera +30 de Sanidade",
        "Você lembra de momentos ruins, perde 10 de Sanidade",
        "Você lembra de momentos ruins, perde 20 de Sanidade",
        "Você lembra de momentos ruins, perde 30 de Sanidade",
        "Você não se sente bem e contrai uma doença",
        "Algo do cenário cai em você",
        "Você tropeça",
        "Você tropeça e acha algo escondido no chão",
        "Você encontra uma carcaça grande",
        "Você encontra uma carcaça pequena",
        "Você encontra uma carcaça média",
        "Você encontra uma carcaça de Apex Predador velho ou morto",
        "Os Deuses não gostaram de você hoje, jogue um dado de efeito",
        "O Deus Ancião não gostou das suas ações hoje, sua mutação é bloqueada temporariamente.",
        "O Deus Ancião gostou das suas ações hoje, se for diabólico, recebe +2 dados de dano contra humanos.",
        "Os Deuses gostaram das suas ações hoje, se tiver religião, ganha +5 em um bônus por 1 dia.",
        "Você se sente com muita fome, a ilha sabe que todos são animais",
        "Você sente sede",
        "Você reflete sobre um cenário em sua mente e ganha uma dica da narrativa.",
        "Você se sente motivado hoje, recebe mais cargas de mutação (1d4)",
        "Você encontra um animal do bioma de sua escolha",
        "Você encontra uma criatura pequena, do bioma",
        "Você encontra um casal pequeno com filhotes do bioma",
        "Você encontra um filhote pequeno indefeso do bioma",
        "Você encontra um animal médio, do bioma",
        "Você encontra um casal médio, com filhotes do bioma",
        "Você encontra um filhote médio indefeso do bioma",
        "Você encontra animais maldosos médios ou pequenos te espreitando",
        "Você encontra um animal grande ou Apex do bioma",
        "Você encontra um casal grande ou Apex do bioma, com filhotes",
        "Você encontra um filhote maldoso grande ou Apex sozinho do bioma",
        "Você encontra um filhote grande ou Apex indefeso do bioma",
        "Sua mente é abalada com um encontro de um APEX Predador",
        "Seu corpo reage contra uma emboscada de um APEX Predador",
        "Vocês são salvos de algum problema por uma manada de herbívoros",
        "Vocês são salvos de um Apex Predador por surgir uma manada APEX de herbívoros",
        "Uma manada surge com filhotes bonzinhos ao lado da base",
        "Desculpe, mas um chefe encontrou vocês...",
    ],

    'efeito' => [
        "Buff do dia, acorda estimulado, +5 em algo",
        "Buff do dia, acorda estimulado, +1 dado em algo",
        "Buff do dia, acorda estimulado, +1 dado de dano",
        "Buff do dia, acorda estimulado, Mana infinita",
        "Buff do dia, acorda estimulado, causa +2 dados de dano em sangramento ou em peste",
        "Nerf do dia, acorda preguiçoso, -5 no bônus mais usável",
        "Nerf do dia, acorda amedrontado, -5 de sanidade sempre que errar",
        "Nerf do dia, acorda defeituoso, -1 dado em vigor e força",
        "Nerf do dia, dor de cabeça, -1 dado de inteligência e sabedoria",
        "Condição, se for mulher, acorda com sangramento, 1d12 de dano de sangramento",
        "Condição, se for homem, acorda distraído, fica marcado a sessão toda",
        "Condição, sortudo, dobro de rolagens em dados de itens, minérios e drops",
        "Condição, destroçado, sobreviveu a um combate intenso, -5 em ações no resto do dia",
        "Condição, protagonista, se sente o especial, fica marcado a sessão toda",
        "Condição, doente, acorda ou fica fraco no resto do dia, recebe 2d6 de dano de peste",
        "Condição, calorento, não consegue usar armaduras sem superaquecer ou cheirar mal no resto do dia",
        "Condição, friento, não consegue ficar sem roupas grossas sem ficar lento, -1 de agilidade",
        "Condição, com fé, pode usar religião em bônus adicionais de testes",
        "Condição, sem fé, é proibido o uso de bônus em equipe durante a sessão",
        "Condição, caçado pelo Lobo, ele está te observando, infelizmente você está exposto no resto da sessão",
        "Condição, tímido, durante a sessão começa qualquer combate com o efeito Furtivo",
        "Condição, Diabólico, se sente solitário e raivoso à noite, se tornando diabólico durante a sessão",
        "Condição, Distorção de mutação, suas mutações possuem chance de evoluir (1d2)",
        "Condição, Alimentado, se sente satisfeito e não precisa comer durante o dia na sessão",
        "Condição, Apaixonado, se sente unido e depende de um jogador, ganhando +5 em uma ação em conjunto com ele",
        "Condição, Amigo dos animais, se sente confortável com dinossauros e tem chance de ser ignorado (1d2) por predadores na cena",
        "Condição, Bondade, cura 30 pontos de vida",
        "Condição, Reflexivo, recupera 30 pontos de sanidade",
    ],

    'minerio' => [
        "Você encontra lascas de Pedra (1d4)",
        "Você encontra lascas de Sílex (1d4)",
        "Você encontra lascas de Carvão (1d4)",
        "Você encontra lascas de Cristal (1d4)",
        "Você encontra um Depósito de Sal (1d4)",
        "Você encontra um pedaço de Âmbar (1d4)",
        "Você encontra lascas de Cobre (1d4)",
        "Você encontra lascas de Ferro (1d4)",
        "Você encontra minério de Enxofre (1d4)",
        "Você encontra lascas de Bronze (1d4)",
    ],

    'raros' => [
        "Você encontra lascas de Titânio (1d4)",
        "Você encontra lascas de Prata (1d4)",
        "Você encontra lascas de Ouro (1d4)",
        "Você encontra lascas de Chumbo (1d4)",
        "Você encontra lascas de Lítio (1d4)",
        "Você encontra minério de Urânio (1d4)",
        "Você encontra lascas de Platina (1d4)",
        "Você encontra pedaços de Obsidiana (1d4)",
    ],

    'drop' => [
        "Masterpod", "Criopod com Criatura Aleatória", "Criopod da Caveira", "Criopod dos Raios", "Criopod das Pestes", "Criopod de Fogo", "Criopod Sirência", "Criopod Elemental", "Criopod de Gelo", "Criopod Gamma", "Criopod Maldita", "Criopod Hypo", "Criopod da Morte", "Orbe dos Ceifadores", "Pedaço de Colosso Esquecido", "Arma Lendária de Arena de Colosso", "Arma Radiante aleatória", "Ovo de Dragão", "Ovo de Dinossauro aleatório C/H", "Ovo de Dinossauro aleatório C/H", "Ovo de Dinossauro aleatório C/H", "Ovo de Dinossauro Selecional C/H", "Ovo de Dinossauro Apex", "Ovo de Leviatã C/H", "Item Raro de Criatura já Vista", "Amuleto de Invocação de Criatura (Escolha com Cuidado)", "Mochila de Consumivel de Cena", "Descanso de Fogueira no Reino dos Esquecidos", "Um Orbe de Pesadelo Lutável", "Uma Medalhão de Guilda da Caçada", "Um dia da Benção da Ovelha na Ilha da Caveira", "Um Meteorito de Minério épico", "Um Meteorito de Minério Raro-Comum Selecionavel", "Bússola do Caídos", "Fragmento de Coroa Dourada", "Arma com Imprint selecionável de minério", "Pedaço de arma Tek", "Pedaço de item Tek", "Pedaço de sela Tek", "Pedaço de máquina Tek", "Saco de jóias 3x", "Chave de Masmorra", "Chave da caveira", "Isca de leviatã selecionável", "Barril de pólvora", "Pólvora Negra", "Lasca de Casco do Inferno", "Planta Básica aleatória", "Um brasão do Tolo", "Convite Real da família Escarlate", "Chip avançado alienígena", "Chave roxa alienígena", "Chave azul alienígena", "Chave laranja alienígena", "Anotação de alienígena", "Livro de rituais comuns", "Livros de ritual brutal de elemento aleatório", "Baú de itens aleatórios 8x", "A Possibilidade de Criar um Título", "Armadura Ideal de personagem", "Item Ideal de Personagem", "Rolar Item Raro Aleatório", "Rolar Item Raro Aleatório", "Rolar Item Raro Aleatório", "Rolar Item Raro Aleatório",
    ],

    'traumas' => [
        "Estressado", "Medroso", "Ganancioso", "Paranoico", "Egoísta", "Estresse Pós-Traumático", "Insano", "Desesperado", "Letárgico", "Fanático", "Degenerado", "Obsessivo", "Delirante", "Silencioso", "Detentor",
    ],

    'epicos' => [
        "Você encontra um Lendário Diamante(1d4)",
        "Você encontra uma Lendária Magnetita(1d4)",
        "Você encontra um Lendário Netherite(1d4)",
        "Você encontra um Lendário Elemento(1d4)",
        "Você encontra uma Lendária Cianita(1d4)",
        "Você encontra um Lendário Módulo de Minério(1d4)",
    ],

    'joias' => [
        "Você encontra uma Jóia de Sáfira",
        "Você encontra uma Jóia de Esmeralda",
        "Você encontra uma Jóia de Rubi",
        "Você encontra uma Jóia de Redstone",
        "Você encontra uma Jóia de Diamante",
        "Você encontra uma Jóia Hypo",
        "Você encontra uma Jóia da Noite",
        "Você encontra uma quantia de Pérolas Sílicas",
        "Você encontra uma quantia de Pérolas Negras ",
    ],

    'joias_raras' => [
        "Você encontra uma Jóia de Elemento",
        "Você encontra uma Jóia de Cristal da Caveira",
        "Você encontra uma Jóia de Cristal do Inferno",
        "Você encontra uma Jóia do Véu",
        "Você encontra uma Jóia de Mefisto",
        "Você encontra um Dente de Lobo Escuro",
        "Você encontra um Pelo liso branco de Ovelha",
        "Você encontra uma Esféra de Ion",
        "Você encontra um Medalão de Ouro Maldito",
        "Você encontra uma Jóia Solar",
    ],

    'circuitos' => [
        "Caixa de Ferramentas",
        "Chip de Alcance",
        "Chip de Eficiência",
        "Sensor de movimento",
        "Sensor de Meteorológico",
        "Sensor de Mana",
        "Sensor de Wi-fi",
        "Chip de Computador Artesão",
        "Fio de Cobre",
        "Bateria",
        "Bateria de Ion",
        "Resistores de Proteção",
        "Módulos de Circuito",
        "Sucatas de Engrenagens",
        "Rótulo de Filtro",
        "Compartimento de Chips",
        "Engrenagens Mecânicas Pesadas",
        "Pistões Hidráulicos",
        "Barril de Pressão / Tanque de Ar",
        "Rotor de Hélice / Turbina",
        "Cabo de Aço Trançado",
        "Molas de Compressão Militar",
        "Célula de Hidrogênio Líquido",
        "Núcleo de Mana Condensada",
        "Fluido de Refrigeração Criogênica",
        "Servo-Motor de Precisão",
        "Scanner de Frequência (Radar / Sonar)",
        "Painel de Interface Holográfica",
        "DNA Sintético Puro",
        "Parafusos Anti-Corrosão",
        "Vidro de Pressão (Cúpula Oceânica)",
        "Placa de Aço Enferrujada",
        "Circuito Alienígena",
        "Bobina de Energia",
        "Caboes Revestidos de Chumbo",
        "Peça de Sucata Espacial",
        "Condutor de Mana-Tek",
        "Núcleo de Reator Danificado",
        "Gel de Combustível Subaquático",
        "Módulo de Decodificação",
        "Fragmento de Satélite Caído",
        "Tampa de Cryo-Core",
        "Metal Compactado Experimental",
        "Um Pedaço Tek quebrado",
    ],

    'crimes' => [
        "Um encontro com um grupo de Bandidos",
        "Um encontro com um bandido",
        "Um encontro com um Meio-humano sendo emboscado",
        "Um encontro com um Ser Diabólico",
        "Um encontro em uma situação de perseguição",
        "Um encontro em uma situação Delicada",
        "Um encontro em uma situação furtiva",
        "Um encontro em uma situação de tráfico de animais",
        "Um encontro com um capanga sozinho",
        "Uma Pista de um possível Caos",
        "Um encontro Brutal com um capanga",
        "Um encontro Brutal com um Grupo de Capangas",
        "Um encontro Brutal com um Chefe de Clã",
        "Uma situação que solicita ajuda",
        "Um encontro com um NPC que tanto espera",
        "Um encontro de Criatura selvagem atacando pessoas",
        "Um interrogatório de um bandido por um motivo",
        "Nada",
        "Nada",
        "Uma briga de bar",
        "Uma briga de Casal intensa",
        "Um roubo em andamento em uma caravana",
        "Um grupo vendendo relíquias roubadas",
        "Um sequestro silencioso em um beco",
        "Um corpo encontrado em circunstâncias misteriosas",
        "Uma emboscada de caçadores de recompensas",
        "Um duelo ilegal acontecendo na rua",
        "Um mercado negro de criaturas exóticas",
        "Um culto realizando um ritual proibido",
        "Um incêndio criminoso consumindo uma vila",
        "Uma gangue cobrando taxas de 'proteção'",
        "Um saque acontecendo após um desastre",
        "Uma criança pedindo ajuda para encontrar alguém",
        "Dois comerciantes brigando por contrabando",
        "Um assassinato testemunhado ao longe",
        "Contrabandistas carregando armas estranhas",
        "Soldados desertores saqueando viajantes",
        "Explosivos plantados em uma estrutura",
        "Um ladrão tentando cortar a bolsa de um aliado",
        "Um julgamento público prestes a acontecer",
        "Uma execução pública prestes a começar",
        "Um animal raro sendo vendido ilegalmente",
        "Uma milícia local interrogando inocentes",
        "Um grupo torturando alguém em um celeiro",
    ],

    'item' => [
        "Pedra",
        "Um Saco de Moedas aleatório 1d10 (Moeda de Prata)",
        "Um Saco de Moedas aleatório 1d4 (Moeda de Ouro)",
        "Sílex",
        "Areia",
        "Pelo Seco",
        "Roupa do Ark Básica",
        "Roupa de Couro com Parte",
        "Roupa do Inverno",
        "Roupa de Banho",
        "Madeira natural",
        "Madeira refinada",
        "palha",
        "Monte grande de Palha",
        "Fibra",
        "Fibra do Campos",
        "Seda",
        "Seda de Inseto",
        "Lã",
        "Lã rara",
        "Quitina comum",
        "Quitina grossa",
        "Quitina rara",
        "Ossos de um dinossauro",
        "Fóssil preservado de um Dinossauro",
        "Parte de dinossauro ou criatura",
        "Couro comunm",
        "Couro de Penas",
        "Couro",
        "Couro de jacaré",
        "Couro de Abelissauro",
        "Couro de Ceratopcideos",
        "Couro de Acrocantosssaurideos",
        "Couro de tiranossaurideos",
        "Couro de raptores",
        "Couro de Handrossaurideos",
        "Couro de Saurópodes",
        "Couro de Espinossaurideos",
        "Couro de Presas",
        "Couro de Dragão",
        "Couro de Criatura da Caveira",
        "Couro de réptil Marinho",
        "Couro de Grupo dos Pterossauros",
        "Couro de Mamiferos",
        "Couro de Criatura Mágica",
        "Couro de Apex predador",
        "Couro de Apex esquecido",
        "Cimento Natural",
        "Cimento Industrial",
        "Resina",
        "Resina vermelha",
        "Ambâr comum",
        "Ambâr do pantâno",
        "Ambâr com inseto",
        "pólvora",
        "pólvora negra",
        "pólvora do véu",
        "Argila",
        "Fertilizante",
        "Caixa de temperos",
        "Pétróleo",
        "óleo",
        "Petróelo Natural rochosso",
        "Pétróelo refinado",
        "Óleo Carmsein",
        "Polimero Orgânico",
        "Polimero industrial",
        "Eletrônico",
        "Eletrônico tek",
        "Eletrônico Quebrado",
        "Criopod vazia",
        "Criopod com Animal comum",
        "Criopod com Animal de A-M aleatório",
        "Criopod com Animal de N-Z aleatório",
        "Criopod com Animal Médio de Seleção",
        "Mapa Rasgado de Explorador",
    ],

    'frutas' => [
        "Amarberry", "Azulberry", "Mejoberry", "Narcoberry", "Stimberry", "Tintoberry", "Planta X", "Semente de Trigo", "Semente de Arroz", "Semente de Soja", "Limão", "Milho", "Cenoura", "Batata", "Maçã", "Banana", "Manga", "Cereja",
    ],

    'navio' => [
        "Uma viagem tranquila sem eventos ou encontros",
        "Uma viagem interrompida. Um temporal atinge o navio",
        "Uma viagem tranquila. Até baterem em uma vela de espinossauro marinho no meio do barco",
        "Uma vigaem tranquila. Até um Karkinos segurar o barco achando que é comida.",
        "Uma viagem tranquila. Até um Leviatã aparecer e atacar o barco",
        "Uma viagem tranquila. Até nada acontecer. Que bom!",
        "Uma vigaem tranquila. Até as maldições do mar arderem e causarem dano aos naufragados. 2D12 de dano Verdadeiro.",
        "Uma viagem tranquila. Até vocês baterem o barco em corais.",
        "Uma viagem tranquila. Até o Mar ficar completamente calmo e sem vento, parando o barco por 1d4 horas.",
        "Uma viagem tranquila. Até o mar ficar quieto demais...",
    ],

    'item_bau' => [
        "Baú Normal - Item de pedra",
        "Baú Vazio - Que Azar",
        "Baú de Pirata - Item de ferro com ouro, 25 moedas de Ouro",
        "Baú de Acumulador - 650 moedas de Ouro, Moeda Maldita",
        "Baú de Acumulador - 250 Moedas de Ouro, Arma de ferro de Ouro",
        "Baú de Acumulador - 100 Moedas de Ouro, Shouldbraker",
        "Baú de Acumulador do Tributo - 700 moedas de Ouro, 250 Moedas de Prata, 100 Moedas de Bronze",
        "Baú dos Caídos - Uma parte de Colosso, Chave de Masmorra",
        "Baú dos Caídos - Uma Arma lendária de Arena de Colosso",
        "Baú dos Caídos - Um ritual de nível diabólico ou menor qualquer de qualquer elemento",
        "Baú dos Caídos - Uma Mutação tema de um Colosso",
        "Baú de Mercador - Uma joia normal 1d4",
        "Baú de Mercador - Uma Arma de Aço com Molde de Armadura",
        "Baú de Mercador - Um Tônico de Efeito Aleatório",
        "Baú de Mercador - 3 itens aleatórios",
        "Baú de Mercador - 3 tipos de couro ou tecido de animal",
        "Baú de Mercador - Pacote de criação de Pacto Caseiro",
        "Baú de Mercador - Pacote de Fertilizantes Companhia Rola-Bosta (1d4)",
        "Baú de Mercador - Pacotes de Bebidas de Luxo (1d8)",
        "Baú de Mercador - Pacotes de Produtos Industrializados (1d4)",
        "Baú do Caçador-Lobo - Pacotes de Munição Selecionável",
        "Baú de Atenas - 300 moedas de Prata e uma Arma Radiante",
        "Baú de Atenas - Joia do Véu e 3 Rituais Brutais de qualquer elemento",
        "Baú de Atenas - Chave de Forte do Véu e 10 Ervas de Alma",
        "Baú de Atenas - Barril de Pó Negro e 1d10 de Lascas de Carvão",
        "Baú de Ceifador - Uma Mutação de Alguém que se foi...",
        "Baú de Ceifador - Caveira de Ashen e um Molde de lava",
        "Baú de Ceifador - Uma reforja de uma Arma nos Ceifadores",
        "Baú do Ceifador - Uma entrega Arriscada para os Ceifadores",
        "Baú do Ceifador - Uma Criatura da Caveira aleatória em uma Criopod de 3 escolhas",
        "Baú do Ceifador - Um Pacto de fogo ou dos Serviçais da Chama",
        "Baú do Ceifador - Um Mel de Magma Único",
        "Baú Hypo - 3 Criaturas Bêbês Médias ou Grandes aleatórias",
        "Baú Hypo - 3 Sementes aleatórias de Plantas",
        "Baú Hypo - Pacote de Ervas e Frutas de biomas 5x d10",
        "Baú Hypo - Melhoria rígida de mutação",
        "Saco de Moedas - 250 Moedas de Prata",
        "Saco de Moedas Nobre - 100 Moedas de Ouro",
        "Baú do Náufrago - 50 moedas de Prata",
        "Baú do Almirante - 10 moedas de Ouro",
        "Baú da Fúria - 100 Moedas de Ouro, um ritual de Fogo ou uma Cicatrização de um membro",
        "Baú do Chorão - 100 moedas de prata, Recupera-se de um trauma qualquer",
        "Chave da Caveira de Forte",
        "Orbe dos Sonhos",
        "Orbe dos Ceifadores - Buff em mutação",
        "Pacote de Joias 1d2 aleatório",
        "Couro de um Apex Predador",
    ],
];